# Generated by Django 5.1.7 on 2025-03-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='linear.issue'),
        ),
    ]
