# Generated by Django 5.2 on 2025-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear', '0003_remove_issue_description_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='overwork_day',
            field=models.BooleanField(default=False),
        ),
    ]
