# Generated by Django 5.2 on 2025-05-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear', '0004_work_overwork_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='wage_month',
            field=models.CharField(blank=True, choices=[('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور'), ('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند')], default='فروردین', max_length=2550, null=True, verbose_name='wage month'),
        ),
    ]
