# Generated by Django 5.2 on 2025-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear', '0005_work_wage_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='url',
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
